Level.TITLE
  .setNextLevel(Level.ONE)
  .setNextLevel(Level.TWO)
  .setNextLevel(Level.THREE)
  .setNextLevel(Level.FOUR)
  .setNextLevel(Level.FIVE)
  .setNextLevel(Level.SIX)
  .setNextLevel(Level.END)
  .setNextLevel(Level.TITLE);
